name: librewolf
title: Librewolf (unofficial)
version: 1.0
license: MPL-2.0
website: https://librewolf.net/
source-code: https://codeberg.org/librewolf
issues: https://github.com/thatLeaflet/librewolf-snap/issues
type: app
icon: snap/gui/librewolf.svg
summary: A custom version of Firefox, focused on privacy, security and freedom
description: |
  This project is an independent fork of Firefox, with the primary goals of privacy security and user freedom. It is the community run successor to LibreFox.

  LibreWolf uses more than 500 privacy/security/performance settings, patches, LibreWolf-Addons (optional) and is designed to minimize data collection and telemetry as much as possible (updater, crashreporter and Firefox’s integrated addons that don’t respect privacy are removed).

  LibreWolf is NOT associated with Mozilla or its products.
  
  Note: This is an unofficial repackaging and is not endorsed by the upstream project.

confinement: strict
base: core22
compression: lzo
grade: stable
architectures:
  - build-on: [amd64]
    build-for: [amd64]

package-repositories:
  - type: apt
    components: [main]
    suites: [jammy]
    key-id: 034F7776EF5E0C613D2F7934D29FBD5F93C0CFC3
    url: https://deb.librewolf.net
    
parts:
  librewolf:
    plugin: nil
    stage-packages: [librewolf, ffmpeg, ubuntu-restricted-extras]
  cleanup:
    after: [librewolf]
    plugin: nil
    build-snaps: [gnome-42-2204]
    override-prime: |
      set -eux
      for snap in "gnome-42-2204"; do  # List all content-snaps you're using here
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" "$SNAPCRAFT_PRIME/usr/{}" \;
      done
      for CRUFT in bug lintian man; do
        rm -rf $SNAPCRAFT_PRIME/usr/share/$CRUFT
      done
      find $SNAPCRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
      find $SNAPCRAFT_PRIME/usr/share -type d -empty -delete

# taken from firefox snapcraft.yaml
plugs:
  browser-sandbox:
    interface: browser-support
    allow-sandbox: true

apps:
  librewolf:
    command: usr/bin/librewolf
    extensions: [gnome]
    environment:
      HOME: "$SNAP_USER_COMMON"
    plugs:
      - audio-playback
      - browser-sandbox
      - home
      - network
      - removable-media # no auto-connect
